language: generic

dist: trusty
sudo: required

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"

cache:
  directories:
    - ${DEPENDENCY_DIR}

services:
  - docker


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-5.0
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
          sources: *sources

before_install:
  - docker pull jorj/clang5_qt5
  - docker  run jorj/clang5_qt5 --name devtest -v .:/mnt /bin/bash -c "${cxx} --version; cmake --version ls /mnt"

install:
  - script/ci_install.sh

script:
  - script/ci_build.sh

