language: minimal

dist: bionic

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"


matrix:
    include:
    - env: COMPILER=gcc-9
    - env: COMPILER=gcc-8
    - env: COMPILER=gcc-7
    - env: COMPILER=clang-9
    - env: COMPILER=clang-8
    - env: COMPILER=clang-7
    - env: COMPILER=clang-6
    - env: COMPILER=clang-5


before_install:
  - docker pull ${DOCKER_IMG}/${COMPILER}:stable

script:
  - docker run --cap-add SYS_PTRACE -v ${PWD}:/mnt -it ${DOCKER_IMG}/${COMPILER} /bin/bash -c "cd /mnt; script/ci_build.sh"

