language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"


matrix:
    include:
    - env: CC=gcc-7
    - env: CC=gcc-6
    - env: CC=clang-5
    - env: CC=clang-4


before_install:
  - docker pull ${DOCKER_IMG}/${CC}:latest
  - docker images

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${CC} /bin/bash -c "cd /mnt; script/ci_build.sh"

