name: ci

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:14
          - gcc:13
          - gcc:12
          - gcc:11
          - clang:20
          - clang:19
          - clang:18
          - clang:17
          - clang:16
          - clang:15
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh

  build_conan:
    runs-on: ubuntu-latest
    container:
      image: "registry.gitlab.com/offa/docker-images/gcc:13"
    name: "conan ${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/conan_build.sh

  formatting-check:
    name: "formatting"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: jidicula/clang-format-action@main
      name: "Verify formatting"
      with:
        clang-format-version: 19

